# -*- coding: utf-8 -*-

from actions.ResponderVacinadosEmUmEstadoAction import ResponderVacinadosEmUmEstadoAction
from actions.ResponderSobreCovidAction import ResponderSobreCovidAction
from actions.ResponderQuantidadeInfectadosPorPeriodoAction import ResponderQuantidadeInfectadosPorPeriodoAction
from actions.ResponderQuantidadeMortosPorPeriodoAction import ResponderQuantidadeMortosPorPeriodoAction